filter
js-tasks-ru/jsbasic-20210325_ilfir803 pull request #5
Opened 2021-04-11 19:15 UTC by ILFIR803

2021-04-11 19:15 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2021-04-12 07:11 UTC, koalex requested changes
Надо исправить замечание

2021-04-12 07:11 UTC, koalex commented on 3-module/2-task/index.js
> +alert(filterRange);
alert надо удалить

2021-04-15 17:40 UTC, ILFIR803 commented on 3-module/2-task/index.js
> +alert(filterRange);
сделано

2021-04-16 02:09 UTC, koalex approved these changes

2021-04-16 02:09 UTC, merged